CREATE TABLE animal (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   nome_provisorio VARCHAR(255) NOT NULL,
   idade_estimada INT NOT NULL,
   raca VARCHAR(255) NOT NULL,
   data_entrada TIMESTAMP NOT NULL,
   data_adocao TIMESTAMP,
   condicoes_chegada VARCHAR(255) NOT NULL,
   nome_recebedor VARCHAR(255) NOT NULL,
   data_obto TIMESTAMP,
   porte VARCHAR(255) NOT NULL,
   CONSTRAINT pk_animal PRIMARY KEY (id)
);